import { v4 as uuidv4 } from 'uuid';
import { RegisteredFlow } from '../../../domain/entities/registered-flow.entity';
import { FlowStatus } from '../../../domain/enums/flow-status.enum';
import { RiskLevel } from '../../../domain/enums/risk-level.enum';

export function getInitialSeedFlows(): RegisteredFlow[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  const hour = 60 * 60 * 1000;

  return [
    new RegisteredFlow(
      uuidv4(),
      'zapier',
      'finanzas',
      FlowStatus.UNDER_REVIEW,
      RiskLevel.MEDIUM,
      {
        flowName: 'Conciliación Bancaria Automática',
        author: 'laura.finanzas@empresa.com',
        trigger: 'bank.transaction.created',
        action: 'quickbooks.sync_entry',
        reviewReason: 'Aislamiento Preventivo de Finanzas',
      },
      new Date(now - 2 * hour),
      new Date(now - 2 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'unknown_tool',
      'operaciones',
      FlowStatus.BLOCKED,
      RiskLevel.CRITICAL,
      {
        flowName: 'Extracción No Homologada de Envíos',
        author: 'externo.dev@partner.com',
        trigger: 'webhook.incoming',
        action: 'database.bulk_dump',
        blockReason: 'Bloqueo de Plataformas No Homologadas',
      },
      new Date(now - 5 * hour),
      new Date(now - 5 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'zapier',
      'marketing',
      FlowStatus.APPROVED,
      RiskLevel.LOW,
      {
        flowName: 'Sincronización de Leads Web a CRM',
        author: 'user@governance.com',
        trigger: 'hubspot.contact.created',
        action: 'salesforce.create_lead',
      },
      new Date(now - 12 * hour),
      new Date(now - 12 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'n8n',
      'it',
      FlowStatus.APPROVED,
      RiskLevel.LOW,
      {
        flowName: 'Alertas de Incidentes Críticos de Jira',
        author: 'devops@empresa.com',
        trigger: 'jira.issue.priority_highest',
        action: 'slack.post_security_alert',
      },
      new Date(now - 1 * day),
      new Date(now - 1 * day),
    ),
    new RegisteredFlow(
      uuidv4(),
      'zapier',
      'ventas',
      FlowStatus.PENDING,
      RiskLevel.LOW,
      {
        flowName: 'Ingreso de Oportunidades Salesforce',
        author: 'carla.ventas@empresa.com',
        trigger: 'salesforce.opportunity.updated',
        action: 'notion.create_page',
      },
      new Date(now - 1 * day - 4 * hour),
      new Date(now - 1 * day - 4 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'power_automate',
      'operaciones',
      FlowStatus.RISKY,
      RiskLevel.HIGH,
      {
        flowName: 'Transferencia de Tokens a Pasarela Externa',
        author: 'soporte.ops@empresa.com',
        trigger: 'ftp.file.uploaded',
        action: 'api.forward_payload',
        warning: 'Detección de Credenciales en Payloads',
      },
      new Date(now - 2 * day),
      new Date(now - 2 * day),
    ),
    new RegisteredFlow(
      uuidv4(),
      'n8n',
      'legal',
      FlowStatus.APPROVED,
      RiskLevel.LOW,
      {
        flowName: 'Archivo Centralizado de Contratos Firmados',
        author: 'abogados@empresa.com',
        trigger: 'docusign.envelope.completed',
        action: 's3.encrypted_store',
      },
      new Date(now - 2 * day - 8 * hour),
      new Date(now - 2 * day - 8 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'zapier',
      'rrhh',
      FlowStatus.APPROVED,
      RiskLevel.LOW,
      {
        flowName: 'Onboarding Automatizado de Nuevos Empleados',
        author: 'talento@empresa.com',
        trigger: 'bamboohr.employee.added',
        action: 'google.create_workspace_account',
      },
      new Date(now - 3 * day),
      new Date(now - 3 * day),
    ),
    new RegisteredFlow(
      uuidv4(),
      'suspicious_bot',
      'finanzas',
      FlowStatus.BLOCKED,
      RiskLevel.CRITICAL,
      {
        flowName: 'Webhook No Autorizado en Servidor de Pagos',
        author: 'unknown@external-ip.net',
        trigger: 'http.raw_post',
        action: 'sql.execute_raw',
        blockReason: 'Bloqueo de Plataformas No Homologadas | Aislamiento Preventivo de Finanzas',
      },
      new Date(now - 3 * day - 6 * hour),
      new Date(now - 3 * day - 6 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'make',
      'marketing',
      FlowStatus.UNDER_REVIEW,
      RiskLevel.MEDIUM,
      {
        flowName: 'Notificación de Campañas por Gmail',
        author: 'user@governance.com',
        trigger: 'make.webhook.campaign',
        action: 'gmail.send_bulk_notification',
        reviewReason: 'Requiere autorización de TI: uso de conector de correo saliente externo',
      },
      new Date(now - 1 * day - 2 * hour),
      new Date(now - 1 * day - 2 * hour),
    ),
    new RegisteredFlow(
      uuidv4(),
      'n8n',
      'marketing',
      FlowStatus.BLOCKED,
      RiskLevel.CRITICAL,
      {
        flowName: 'Backup de Base de Clientes a Dropbox Personal',
        author: 'user@governance.com',
        trigger: 'hubspot.export_contacts',
        action: 'dropbox.personal_upload',
        blockReason: 'Bloqueado por política: transferencia no autorizada de datos sensibles fuera de OneDrive/SharePoint',
      },
      new Date(now - 2 * day - 4 * hour),
      new Date(now - 2 * day - 4 * hour),
    ),
  ];
}

